import { unitIdSchema } from "@workspace/game-domain"

// Slugs that diverge from the default camelCase→snake_case derivation.
// All other character ids derive cleanly as camelCase→snake_case.
export const characterIconOverrides = new Map([
  [unitIdSchema.parse("astraPrimarisPsy"), "astra_psyker"],
  [unitIdSchema.parse("bloodDeathCompany"), "blood_deathcompany"],
  [unitIdSchema.parse("custoBladeChampion"), "custo_bladechampion"],
  [unitIdSchema.parse("custoVexilusPraetor"), "custo_vexilus"],
  [unitIdSchema.parse("eldarAutarch"), "aelda_autarch"],
  [unitIdSchema.parse("eldarFarseer"), "aelda_farseer"],
  [unitIdSchema.parse("eldarJainZar"), "aelda_jainzar"],
  [unitIdSchema.parse("eldarMauganRa"), "aelda_maugan"],
  [unitIdSchema.parse("eldarRanger"), "aelda_ranger"],
  [unitIdSchema.parse("emperFlawlessBlade"), "emper_blade"],
  [unitIdSchema.parse("emperNoiseMarine"), "emper_noisemarine"],
  [unitIdSchema.parse("necroDestroyer"), "necro_hexmark"],
  [unitIdSchema.parse("orksBigMek"), "orkss_mek"],
  [unitIdSchema.parse("orksKillaKan"), "orkss_killakan"],
  [unitIdSchema.parse("orksNob"), "orkss_nob"],
  [unitIdSchema.parse("orksRuntherd"), "orkss_runtherd"],
  [unitIdSchema.parse("orksWarboss"), "orkss_warboss"],
  [unitIdSchema.parse("spaceBlackmane"), "space_ragnar"],
  [unitIdSchema.parse("spaceRockfist"), "space_arjac"],
  [unitIdSchema.parse("spaceWolfPriest"), "space_wolfpriest"],
  [unitIdSchema.parse("tauAunShi"), "tauta_aunshi"],
  [unitIdSchema.parse("tauCrisis"), "tauta_crisis"],
  [unitIdSchema.parse("tauDarkstrider"), "tauta_darkstrider"],
  [unitIdSchema.parse("tauFarsight"), "tauta_farsight"],
  [unitIdSchema.parse("tauMarksman"), "tauta_marksman"],
  [unitIdSchema.parse("tauShadowsun"), "tauta_shadowsun"],
  [unitIdSchema.parse("templSwordBrother"), "templ_brother"],
  [unitIdSchema.parse("thousInfernalMaster"), "thous_infernal"],
  [unitIdSchema.parse("tyranTyrantGuard"), "tyran_tyrantguard"],
  [unitIdSchema.parse("tyranWingedPrime"), "tyran_wingedprime"],
  [unitIdSchema.parse("ultraEliminatorSgt"), "ultra_eliminator"],
  [unitIdSchema.parse("ultraInceptorSgt"), "ultra_inceptor"],
])
