import { useCallback } from "react"
import { useTranslation } from "react-i18next"

/**
 * Rules-text resolution for raid-boss abilities and traits, from the en-only id-keyed
 * `raidBossAbilityText` / `raidBossTraitText` game-data namespaces (generated by
 * `scripts/generate-raid-boss-i18n.mjs`). The served `raid-bosses` dataset carries ids only; the
 * `{[variable]}` tokens in a description are resolved against these tables per progression step.
 */

export type RaidBossAbilityTextEntry = {
  description: string
  variables: Record<string, (string | number)[]>
  constants: Record<string, string>
  /** Variable names multiplied by the rarity factor when rendered. */
  scaled: string[]
}

export type RaidBossTraitTextEntry = {
  description: string
  styledName: string
  variables: Record<string, (string | number)[]>
}

export function useRaidBossText() {
  const { i18n } = useTranslation(["raidBossAbilityText", "raidBossTraitText"])

  const abilityText = useCallback(
    (abilityId: string): RaidBossAbilityTextEntry | undefined =>
      (i18n.getResource(i18n.language, "raidBossAbilityText", abilityId) ??
        i18n.getResource("en", "raidBossAbilityText", abilityId)) as
        RaidBossAbilityTextEntry | undefined,
    [i18n]
  )

  const traitText = useCallback(
    (traitId: string): RaidBossTraitTextEntry | undefined =>
      (i18n.getResource(i18n.language, "raidBossTraitText", traitId) ??
        i18n.getResource("en", "raidBossTraitText", traitId)) as
        RaidBossTraitTextEntry | undefined,
    [i18n]
  )

  return { abilityText, traitText }
}
