export {
  servedDatasetKeys,
  isServedDatasetKey,
  catalogManifestMetadataKey,
  type GameCatalogDatasetKey,
  type GameCatalogManifest,
  type GameCatalogManifestDataset,
  type GameCatalogDatasetEnvelope,
  type GameCatalogDatasetMetadata,
  type GameCatalogRecordByKey,
  type GameCatalogCharacterView,
  type GameCatalogNpc,
  type GameCatalogMow,
  type GameCatalogUpgradeView,
  type GameCatalogEquipment,
  type GameCatalogCampaignDefinitionView,
  type GameCatalogLreView,
} from "./types"

export type {
  GameCatalogCampaignBattleView,
  GameCatalogLreTrackView,
  GameCatalogLreBattle,
  GameCatalogLreBattleView,
  GameCatalogLreCommon,
  GameCatalogLreWave,
  GameCatalogLreEnemy,
  GameCatalogFarmLocation,
  GameCatalogUpgradeRecipeIngredient,
  GameCatalogMowUpgradeCost,
  GameCatalogEquipmentUpgradeCost,
} from "./record-types"

export {
  manifestSchema,
  datasetEnvelopeMetaSchema,
  datasetPayloadSchemas,
} from "./schemas"

export {
  GameCatalogHttpClient,
  type GameCatalogClient,
  type GameCatalogManifestResult,
} from "./game-catalog-api"

export {
  syncGameCatalog,
  selectChangedDatasets,
  type GameCatalogSyncResult,
  type GameCatalogSyncProgress,
  type GameCatalogSyncOptions,
} from "./game-catalog-sync"

export {
  getGameCatalogMetadata,
  getManifestMetadata,
  hasCompleteGameCatalogCache,
  clearGameCatalogDb,
  type StoredRecord,
  type CharacterRecord,
  type UpgradeRecord,
  type CampaignBattleRecord,
  type CampaignDefinitionRecord,
} from "./game-catalog-storage"

export {
  Rarity,
  rarityOrder,
  rarityRank,
  rarityClass,
  Rank,
  rankOrder,
  firstRank,
  lastRank,
  currentMaxRank,
  rankIndex,
  rankAt,
  isRank,
  isAdamantineRank,
  Alliance,
  allianceOrder,
  allianceRank,
  factionOrder,
  factionRank,
  groupByFaction,
  type FactionGroup,
  type FactionGroupMember,
  type CharacterId,
  type UpgradeId,
  type FactionId,
  type BattleId,
  type CampaignGroupId,
  ASSET_BASE_PATH,
  UpgradeIcons,
  rarityIcon,
  rankIcon,
  characterIcon,
  campaignIcon,
  campaignDescriptor,
  type CampaignDescriptor,
  type CampaignDifficultyToken,
  traitIcon,
  damageTypeIcon,
  equipmentSlotIcon,
  statIcon,
  type StatIconKind,
  progressionVisual,
  type ProgressionVisual,
  rarityStarsOrder,
  firstRarityStars,
  lastRarityStars,
  rarityStarsIndex,
  isRarityStars,
  progressionOrder,
  firstProgression,
  lastProgression,
  progressionIndex,
  isProgression,
  progressionAt,
  progressionRarity,
  progressionStars,
  statAtRank,
  maxRankForProgression,
  minProgressionForRank,
  type RarityStars,
  type Progression,
} from "./game-entities"
