export {
  servedDatasetKeys,
  isServedDatasetKey,
  catalogManifestMetadataKey,
  type GameCatalogDatasetKey,
  type GameCatalogManifest,
  type GameCatalogManifestDataset,
  type GameCatalogDatasetEnvelope,
  type GameCatalogDatasetMetadata,
  type GameCatalogRecordByKey,
  type GameCatalogCharacterView,
  type GameCatalogNpc,
  type GameCatalogMow,
  type GameCatalogUpgradeView,
  type GameCatalogEquipment,
  type GameCatalogCampaignDefinitionView,
  type GameCatalogLreView,
} from "./types"

export type {
  GameCatalogCampaignBattleView,
  GameCatalogLreTrackView,
  GameCatalogLreBattle,
  GameCatalogLreBattleView,
  GameCatalogLreCommon,
  GameCatalogLreWave,
  GameCatalogLreEnemy,
  GameCatalogFarmLocation,
  GameCatalogUpgradeRecipeIngredient,
  GameCatalogMowUpgradeCost,
  GameCatalogEquipmentUpgradeCost,
} from "./record-types"

export {
  manifestSchema,
  datasetEnvelopeMetaSchema,
  datasetPayloadSchemas,
} from "./schemas"

export {
  GameCatalogHttpClient,
  type GameCatalogClient,
  type GameCatalogManifestResult,
} from "./game-catalog-api"

export {
  syncGameCatalog,
  selectChangedDatasets,
  type GameCatalogSyncResult,
  type GameCatalogSyncProgress,
  type GameCatalogSyncOptions,
} from "./game-catalog-sync"

export {
  getGameCatalogMetadata,
  getManifestMetadata,
  hasCompleteGameCatalogCache,
  getDatasetRecords,
  getDatasetRecord,
  clearGameCatalogDb,
  type GameCatalogStoredRecord,
  type StoredRecord,
} from "./game-catalog-storage"

export {
  GameCatalogProvider,
  useGameCatalogStatus,
  useDatasetRecords,
  type GameCatalogStatus,
  type GameCatalogContextValue,
  type GameCatalogProviderProps,
} from "./game-catalog-context"

export {
  Rarity,
  rarityOrder,
  rarityRank,
  rarityClass,
  Rank,
  rankOrder,
  firstRank,
  lastRank,
  rankIndex,
  rankAt,
  isRank,
  isAdamantineRank,
  Alliance,
  allianceOrder,
  allianceRank,
  factionOrder,
  factionRank,
  groupByFaction,
  type FactionGroup,
  type FactionGroupMember,
  type CharacterId,
  type UpgradeId,
  type FactionId,
  type BattleId,
  type CampaignGroupId,
  upgradeIcon,
  upgradeIconFallback,
  upgradeUnderlay,
  upgradeFrameIcon,
  craftedUpgradeBadge,
  rarityIcon,
  rankIcon,
  characterIcon,
  campaignIcon,
  campaignLabel,
  campaignShortLabel,
  type CampaignShortLabel,
  traitIcon,
  damageTypeIcon,
  damageTypeLabel,
  equipmentSlotIcon,
  equipmentSlotLabel,
  statIcon,
  type StatIconKind,
  progressionVisual,
  type ProgressionVisual,
  rarityStarsOrder,
  firstRarityStars,
  lastRarityStars,
  rarityStarsIndex,
  isRarityStars,
  progressionOrder,
  firstProgression,
  lastProgression,
  progressionIndex,
  isProgression,
  progressionRarity,
  progressionStars,
  statAtRank,
  maxRankForProgression,
  minProgressionForRank,
  type RarityStars,
  type Progression,
} from "./game-entities"
